[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1.0.0", features = ["deref"] }
dotenv = "0.15.0"
itertools = "0.13.0"
reqwest = { version = "0.12.9", features = ["blocking"] }
strum = "0.26.3"
