[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
dotenv = "0.15.0"
env_logger = "0.11.5"
glam = "0.29.2"
itertools = "0.13.0"
log = "0.4.22"
nom = "7.1.3"
ratatui = "0.29.0"
reqwest = { version = "0.12.9", features = ["blocking"] }
